-- Admin Account Migration Script
-- Purpose: Remove duplicate user and update admin credentials

-- Step 1: Find and display duplicate user (Consultor role)
SELECT id, email, name, role 
FROM "User" 
WHERE email = 'maxhigareda@thestoreintelligence.com' 
  AND role = 'CONSULTOR';

-- Step 2: Delete duplicate user (Consultor)
DELETE FROM "User" 
WHERE email = 'maxhigareda@thestoreintelligence.com' 
  AND role = 'CONSULTOR';

-- Step 3: Find current admin account
SELECT id, email, name, role 
FROM "User" 
WHERE role = 'ADMIN';

-- Step 4: Update admin credentials
-- Password hash for 'admin2026' using bcrypt (rounds=10)
-- Generated with: bcrypt.hash('admin2026', 10)
UPDATE "User"
SET 
  email = 'maxhigareda@thestoreintelligence.com',
  password = '$2b$10$YourHashHere' -- This will be generated by script
WHERE role = 'ADMIN';

-- Step 5: Verify the update
SELECT id, email, name, role 
FROM "User" 
WHERE email = 'maxhigareda@thestoreintelligence.com';
